name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      required-value:
        description: "required value"
        required: true
      optional-value:
        description: "optional value"
        required: false
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.inputs.required-value }}
      - run: echo ${{ github.event.inputs.optional-value }}
